lista_telefonica/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('phones.urls')), 
    path('admin/', admin.site.urls),
]

phones/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'phones'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:phone_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
]

phones/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Cria a Model e seus atributos.
class Phone(models.Model):
	name = models.CharField(max_length=200, blank=False)
	email = models.EmailField(blank=True)
	phone_number = PhoneNumberField(blank=False)
	address = models.CharField(max_length=200, blank=True)

phones/forms.py
from django.db import models
from django.forms import ModelForm
from .models import Phone
from django.forms import ModelForm

class PhoneForm(ModelForm):
    class Meta:
        model = Phone
        fields = '__all__'

phones/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Phone
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.forms import modelformset_factory
from django.shortcuts import redirect
from django.contrib import messages
import django_filters
from .filters import PhoneFilter
from .forms import PhoneForm

def index(request):
	phones_list = Phone.objects.all().order_by('name') # Pega todos os objetos de Phone
	phones_filter = PhoneFilter(request.GET, queryset=phones_list) # Filtra os objetos pelo nome que foi escrito
	if phones_list:
		return render(request, 'phones/index.html', {'filter': phones_filter, 'phones_list': phones_list})
	else:
		return render(request, 'phones/index.html', {'filter': "", 'phones_list': ""})

	

def detail(request, phone_id):
	item = get_object_or_404(Phone, pk=phone_id)
	if request.method == 'POST': #verifica o método utilizado
		form = PhoneForm(request.POST or None, instance=item)
		if 'edit_button' in request.POST: # se o botão utilizado foi o de edição
			if form.is_valid(): # verifica se o formulário é válido
					form.save()
					messages.success(request, 'Contato editado com sucesso!')
					return redirect('phones:index')

		if 'delete_button' in request.POST:
				item = Phone.objects.get(pk=phone_id)
				item.delete()
				messages.warning(request, 'Contato excluído com sucesso!')
				return redirect('phones:index')
	else:
		form = PhoneForm(instance=item)
	return render(request, 'phones/detail.html', {'form': form})


def add(request):
	if request.method == 'POST':
		form = PhoneForm(request.POST)
		if form.is_valid():
			form.save()  
			messages.success(request, 'Contato criado com sucesso!')
			return redirect('phones:index')
	else:
		form = PhoneForm()
	return render(request, 'phones/add.html', {'form': form})
'''
def search(request):
	phones_list = Phone.objects.all()
	phones_filter = PhoneFilter(request.GET, queryset=phones_list)
	return render(request, 'phones/search.html', {'filter': phones_filter})
'''

phones/templates/phones/add.html
{% load static %}
{% load bootstrap %}
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="/static/fa/css/all.min.css">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>Adicionar Contato</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    

    <style>
      
        body {
          background-image: url(/static/img/photo_phone3.jfif);
          background-repeat: no-repeat;
          background-attachment: fixed;
          /* e agora a regra de ouro que fará a imagem ocupar todo o viewport */
          background-size: 100% 100%;
        }
    

    </style>

</head>

<body>
<br>
<br>
<br>

 <main class="container bg-light" >
    <div class="container">
        <h1>Adicionar Contato</h1>
        <div>
            <form action="." method="POST" id="Form1">
                {% csrf_token %}
                {{ form|bootstrap }}
                <input type="submit" id="edit_button" name="edit_button" class="btn btn-primary" value="Salvar">
                <a href="{% url 'phones:index' %} ">
                	<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </a>

            </form>
            
        </div>
    </div>
    <br>
</main>

<br>
<br>
<br>

</body>

</html>

phones/templates/phones/detail.html
{% load static %}
{% load bootstrap %}
<!DOCTYPE html>

  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="/static/fa/css/all.min.css">
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <title>Editar Contato</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

      <style>

        body {
          background-image: url(/static/img/photo_phone3.jfif);
          background-repeat: no-repeat;
          background-attachment: fixed;
          background-size: 100% 100%;
        }

      </style>
      
  </head>

  <body>
  <br>
  <br>
  <br>

    <main class="container bg-light" >

      <div class="container class=""">
          <h1>Editar Contato</h1>
          <div>
              <form action="." method="POST" id="Form1">
                  {% csrf_token %}
                  {{ form|bootstrap }}
                  <input type="submit" id="edit_button" name="edit_button" class="btn btn-primary" value="Salvar">
                  <div type="submit" id="element" name="delete_button" class="btn btn-danger show-modal "> Deletar </div>
                  <a href="{% url 'phones:index' %} ">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                  </a>
              </form>
          </div>
      </div>
      <br>
      <!-- Modal -->
      <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Excluir contato</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Ao deletar um contato a ação não pode ser desfeita. Deseja continuar e deletar?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
              <form id="Form1" method="post" action="">
                      {% csrf_token %}
                      <input type="submit"  name="delete_button" class="btn btn-danger show-modal " value="Deletar">
              </form>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
  <br>
  <br>
  <br>
</html>

<script type="text/javascript">

 
  $(document).ready(function(){
    var show_btn=$('.show-modal');
    var show_btn=$('.show-modal');
    
      show_btn.click(function(){
        $("#deleteModal").modal('show');
    })
  });

  $(function() {
        $('#element').on('click', function( e ) {
            Custombox.open({
                target: '#deleteModal',
                effect: 'fadein'
            });
            e.preventDefault();
        });
    });
</script>

phones/templates/phones/index.html
{% load static %}
{% load widget_tweaks %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Lista Telefônica</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="/static/fa/css/all.min.css">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Bootstrap core CSS -->
    <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	    <!-- Favicons -->
  	<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  	<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  	<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  	<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
  	<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  	<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
  	<meta name="theme-color" content="#7952b3">
  	<link rel="stylesheet" href="{% static 'plugins/datepicker/datepicker3.css' %}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/Scroller/css/dataTables.scroller.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/FixedColumns/css/fixedColumns.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/Select/css/select.dataTables.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/Buttons/css/buttons.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/Highlight/dataTables.searchHighlight.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      p {indent-text: 5em;}

      .icon_middle span {
        display:block;
      }
      body {
        background-image: url(/static/img/photo_phone3.jfif);
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
      }
    
    </style>

  </head>

  {% for message in messages %}
  <div class="col-md-4 offset-md-4">
    <div class="alert {{message.tags}} alert-dismissible" role="alert" >
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  </div>
  {% endfor %}

  <body >
  <br>
  <br>
  <br>
    <main class="container bg-light" >
     <h6 class="border-bottom pb-2 mb-0"></h6>
      <div class="my-3 p-3 bg-body rounded shadow-sm">   
        <div class="d-flex justify-content-between border-bottom pb-2 mb-0">
          <h4 class="">Lista Telefônica</h4>
            <a class="btn btn-light" href="{% url 'phones:add' %}" role="button"><i class="fa fa-plus fa-2x" aria-hidden="true" ></i></a>  
        </div>
     
        {% if filter.qs.count %}
        {% for phone in filter.qs %}
          <div class="d-flex text-muted pt-3">
            <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
              <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">&nbsp;{{phone.name}}</strong>
                <a href="{% url 'phones:detail' phone.id %}"><i class="fa fa-cog" aria-hidden="true">&nbsp;Edit </i></i></a>
              </div>
              <span class="d-block">{{phone.phone_number}}</span>
              <span class="d-block">{{phone.email}}</span>
              <span class="d-block">{{phone.address}}</span>
            </div>
          </div>
        {% endfor %}
        {% else %}
        <div class="d-flex text-muted pt-3">
            <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
              <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">&nbsp;Não existem números ainda!</strong>
              </div>
        
            </div>
          </div>
          {% endif %}
        </div>
        <div class="my-3 p-3 bg-body rounded shadow-sm">
          <div class="">
            <h5 class="border-bottom pb-2 mb-0">Pesquisar contato por nome:</h5>
            <br>
            <form method="get">
              <div class="form-group col-sm-4 col-md-3">
                {% render_field filter.form.name class="form-control" %}
              </div>
              <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-search"></span> Pesquisar
              </button>
              <a href="{% url 'phones:index' %} ">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Limpar Filtro</button>
                  </a>
            </form>
          </div>
          <small class="d-block text-end mt-3">
          </small>
        </div>
      </div>
    </main>
    <br>
    <br>
    <br>
  </body>
</html>

  <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

phones/templates/phones/search.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Lista Telefônica</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="/static/fa/css/all.min.css">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Bootstrap core CSS -->
    <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
      <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    <link rel="stylesheet" href="{% static 'plugins/datepicker/datepicker3.css' %}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/Scroller/css/dataTables.scroller.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/FixedColumns/css/fixedColumns.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/Select/css/select.dataTables.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/Buttons/css/buttons.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/Highlight/dataTables.searchHighlight.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      p {indent-text: 5em;}

    .icon_middle span {
        display:block;
    }
    body {
      background-image: url(/static/img/photo_phone3.jfif);
      background-repeat: no-repeat;
      background-attachment: fixed;
      /* e agora a regra de ouro que fará a imagem ocupar todo o viewport */
      background-size: 100% 100%;
    }
    

    </style>
  </head>

  <body  >
   
    <main class="container bg-light" >
    <!--
    <div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm" width="48" height="200" ">
      <img class="me-3" src="" alt="" width="48" height="200">
      <div class="lh-1" width="48" height="200">
        <h1 class="h6 mb-0 text-white lh-1">Bootstrap</h1>
        <small>Since 2011</small>
      </div>
    </div>
    
        <div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
        <img class="me-3" src="/docs/5.0/assets/brand/bootstrap-logo-white.svg" alt="" width="48" height="38">
        <div class="lh-1">
          <h1 class="h6 mb-0 text-white lh-1" >Bootstrap</h1>
          <small>Since 2011</small>
        </div>
      </div>-->
    

     <h6 class="border-bottom pb-2 mb-0"></h6>
      <div class="my-3 p-3 bg-body rounded shadow-sm">   
        <div class="d-flex justify-content-between border-bottom pb-2 mb-0">
          <h4 class="">Lista Telefônica</h4>
            <a class="btn btn-light" href="{% url 'phones:add' %}" role="button"><i class="fa fa-plus fa-2x" aria-hidden="true" ></i></a>  
            <div class="container">
        <h1>Editar Contato</h1>
        <div>
            <form action="." method="POST" id="Form1">
                {% csrf_token %}
                {{ form|bootstrap }}
                <input type="submit" id="edit_button" name="edit_button" class="btn btn-primary" value="Salvar">
                <div type="submit" id="element" name="delete_button" class="btn btn-danger show-modal "> Deletar </div>
                <!--<input type="submit"  name="delete_button" class="btn btn-danger show-modal " value="Deletar">-->
                <a href="{% url 'phones:index' %} ">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </a>


            </form>
            
        </div>
    </div>
    <br>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Excluir contato</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Ao deletar um contato a ação não pode ser desfeita. Deseja continuar e deletar?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <form id="Form1" method="post" action="">
                {% csrf_token %}
                <input type="submit"  name="delete_button" class="btn btn-danger show-modal " value="Deletar">
        </form>
        
      </div>
    </div>
  </div>
</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
        </div>
      </div>

        
      

      
      
    </main>
  </body>


  <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</html>